### ISSUE TITLE
wcpr crashes on Arch Linux

### ISSUE THREAD

**Issue by ikarus23** [mossmann/clock-recovery#3]
```
Traceback (most recent call last):
  File "./wpcr.py", line 94, in <module>
    symbols=wpcr(samples)
  File "./wpcr.py", line 43, in wpcr
    d = numpy.diff(b)**2
  File "/usr/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1926, in diff
    return a[slice1]-a[slice2]
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```
Looks like there are issues within the following construct because `d` has not the right types for the subtraction in `numpy.diff()` (boolean instead of numerical).
```
b = a > midpoint(a)
d = numpy.diff(b)**2
```

**Comment by mossmann** [comment]
Thanks! Fixed in 565dadf.
